In [1]:
import numpy as np

In [11]:
l1 = [1,2,3,4]

In [12]:
arr = np.array(l1)

In [13]:
arr

array([1, 2, 3, 4])

In [14]:
l2 = [5,6,7,8]

In [15]:
l = [l1,l2]

In [16]:
arr1 = np.array(l)

In [17]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr1.shape

(2, 4)

In [19]:
arr1.dtype

dtype('int64')

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Identity Matrix

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Range

In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [31]:
arr = np.arange(0,10)

In [32]:
arr[8]

8

In [33]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [34]:
arr[0:5] = 10

In [35]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

Slice an array

In [36]:
arr_sl = arr[0:5]

In [37]:
arr_sl

array([10, 10, 10, 10, 10])

In [38]:
arr_sl[:] = 5

In [39]:
arr_sl

array([5, 5, 5, 5, 5])

Copy an array

In [40]:
arr_cp = arr.copy()

In [41]:
arr_cp

array([5, 5, 5, 5, 5, 5, 6, 7, 8, 9])

Two dimensional array